export const GET_EPISODE_RATING_START = 'GET_EPISODE_RATING_START';
export const GET_EPISODE_RATING_SUCCESS = 'GET_EPISODE_RATING_SUCCESS';
export const GET_EPISODE_RATING_FAILURE = 'GET_EPISODE_RATING_FAILURE';

export type GET_EPISODE_RATING_START = typeof GET_EPISODE_RATING_START;
export type GET_EPISODE_RATING_SUCCESS = typeof GET_EPISODE_RATING_SUCCESS;
export type GET_EPISODE_RATING_FAILURE = typeof GET_EPISODE_RATING_FAILURE;
