
export const DELETE_SELF_START = 'DELETE_SELF_START';
export const DELETE_SELF_SUCCESS = 'DELETE_SELF_SUCCESS';
export const DELETE_SELF_FAILUR = 'DELETE_SELF_FAILUR';

export type DELETE_SELF_START = typeof DELETE_SELF_START;
export type DELETE_SELF_SUCCESS = typeof DELETE_SELF_SUCCESS;
export type DELETE_SELF_FAILUR = typeof DELETE_SELF_FAILUR;
