export const FETCH_FILTERS_START = 'FETCH_FILTERS_START';
export const FETCH_FILTERS_SUCCESS = 'FETCH_FILTERS_SUCCESS';
export const FETCH_FILTERS_FAILURE = 'FETCH_FILTERS_FAILURE';

export type FETCH_FILTERS_START = typeof FETCH_FILTERS_START;
export type FETCH_FILTERS_SUCCESS = typeof FETCH_FILTERS_SUCCESS;
export type FETCH_FILTERS_FAILURE = typeof FETCH_FILTERS_FAILURE;
