export const FETCH_FILTERS_START = 'FETCH_FILTERS_START';
export const FETCH_FILTERS_SUCCESS = 'FETCH_FILTERS_SUCCESS';
export const FETCH_FILTERS_FAILUR = 'FETCH_FILTERS_FAILUR';

export type FETCH_FILTERS_START = typeof FETCH_FILTERS_START;
export type FETCH_FILTERS_SUCCESS = typeof FETCH_FILTERS_SUCCESS;
export type FETCH_FILTERS_FAILUR = typeof FETCH_FILTERS_FAILUR;
