export const GET_NOTIFICATIONS_START = 'GET_NOTIFICATIONS_START';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILURE = 'GET_NOTIFICATIONS_FAILURE';

export type GET_NOTIFICATIONS_START = typeof GET_NOTIFICATIONS_START;
export type GET_NOTIFICATIONS_SUCCESS = typeof GET_NOTIFICATIONS_SUCCESS;
export type GET_NOTIFICATIONS_FAILURE = typeof GET_NOTIFICATIONS_FAILURE;
