export const RATE_EPISODE_START = 'RATE_EPISODE_START';
export const RATE_EPISODE_SUCCESS = 'RATE_EPISODE_SUCCESS';
export const RATE_EPISODE_FAILURE = 'RATE_EPISODE_FAILURE';

export type RATE_EPISODE_START = typeof RATE_EPISODE_START;
export type RATE_EPISODE_SUCCESS = typeof RATE_EPISODE_SUCCESS;
export type RATE_EPISODE_FAILURE = typeof RATE_EPISODE_FAILURE;
