# Use a lighter version of Node as a parent image
FROM mhart/alpine-node:11 as builder
# Set the working directory to /client
WORKDIR /client
# copy package.json into the container at /client
COPY package*.json /client/
# Copy the current directory contents into the container at /client
COPY . /client/
# install dependencies
RUN yarn
# build css from scss
RUN yarn run build-css
# production build
RUN yarn run build
# use nginx
FROM nginx:latest
#copy build to be served with nginx
COPY --from=builder /client/build /usr/share/nginx/html
# copy default nginx config
COPY --from=builder /client/default.conf /etc/nginx/conf.d/default.conf
# Make the port available to the world outside this container
ENV PORT=3000
# Make the port available to the world outside this container
EXPOSE $PORT