export const GET_PODCAST_EPISODES_START = 'GET_PODCAST_EPISODES_START';
export const GET_PODCAST_EPISODES_SUCCESS = 'GET_PODCAST_EPISODES_SUCCESS';
export const GET_PODCAST_EPISODES_FAILURE = 'GET_PODCAST_EPISODES_FAILURE';

export type GET_PODCAST_EPISODES_START = typeof GET_PODCAST_EPISODES_START;
export type GET_PODCAST_EPISODES_SUCCESS = typeof GET_PODCAST_EPISODES_SUCCESS;
export type GET_PODCAST_EPISODES_FAILURE = typeof GET_PODCAST_EPISODES_FAILURE;
