export const TOGGLE_LOGIN_MODAL = 'TOGGLE_LOGIN_MODAL';
export const TOGGLE_PLAYBACK_MODAL = 'TOGGLE_PLAYBACK_MODAL';
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const TOGGLE_USER_MODAL = 'TOGGLE_USER_MODAL';
export const TOGGLE_NOTIFICATIONS_MODAL = 'TOGGLE_NOTIFICATIONS_MODAL';
export const TOGGLE_MORE_OPTIONS_MODAL = 'TOGGLE_MORE_OPTIONS_MODAL';
export const TOGGLE_RECOMMEND_TO_USER_MODAL = 'TOGGLE_RECOMMEND_TO_USER_MODAL';
export const SET_HEIGHT = 'SET_HEIGHT';

export type TOGGLE_LOGIN_MODAL = typeof TOGGLE_LOGIN_MODAL;
export type TOGGLE_PLAYBACK_MODAL = typeof TOGGLE_PLAYBACK_MODAL;
export type TOGGLE_MENU = typeof TOGGLE_MENU;
export type TOGGLE_USER_MODAL = typeof TOGGLE_USER_MODAL;
export type TOGGLE_NOTIFICATIONS_MODAL = typeof TOGGLE_NOTIFICATIONS_MODAL;
export type TOGGLE_MORE_OPTIONS_MODAL = typeof TOGGLE_MORE_OPTIONS_MODAL;
export type TOGGLE_RECOMMEND_TO_USER_MODAL = typeof TOGGLE_RECOMMEND_TO_USER_MODAL;
export type SET_HEIGHT = typeof SET_HEIGHT;
