const ActionTypes = {
  TOGGLE_LOGIN_MODAL: 'TOGGLE_LOGIN_MODAL',
  TOGGLE_PLAYBACK_MODAL: 'TOGGLE_PLAYBACK_MODAL',
  TOGGLE_MENU: 'TOGGLE_MENU',
  SET_HEIGHT: 'SET_HEIGHT',

};

export default ActionTypes;
