export const GET_TOP_PODCASTS_START = 'GET_TOP_PODCASTS_START';
export const GET_TOP_PODCASTS_SUCCESS = 'GET_TOP_PODCASTS_SUCCESS';
export const GET_TOP_PODCASTS_FAILURE = 'GET_TOP_PODCASTS_FAILURE';

export type GET_TOP_PODCASTS_START = typeof GET_TOP_PODCASTS_START;
export type GET_TOP_PODCASTS_SUCCESS = typeof GET_TOP_PODCASTS_SUCCESS;
export type GET_TOP_PODCASTS_FAILURE = typeof GET_TOP_PODCASTS_FAILURE;
