export const GET_FOLLOWS_START = 'GET_FOLLOWS_START';
export const GET_FOLLOWS_SUCCESS = 'GET_FOLLOWS_SUCCESS';
export const GET_FOLLOWS_FAILURE = 'GET_FOLLOWS_FAILURE';

export type GET_FOLLOWS_START = typeof GET_FOLLOWS_START;
export type GET_FOLLOWS_SUCCESS = typeof GET_FOLLOWS_SUCCESS;
export type GET_FOLLOWS_FAILURE = typeof GET_FOLLOWS_FAILURE;
