export const GET_PODCAST_START = 'GET_PODCAST_START';
export const GET_PODCAST_SUCCESS = 'GET_PODCAST_SUCCESS';
export const GET_PODCAST_FAILURE = 'GET_PODCAST_FAILURE';

export type GET_PODCAST_START = typeof GET_PODCAST_START;
export type GET_PODCAST_SUCCESS = typeof GET_PODCAST_SUCCESS;
export type GET_PODCAST_FAILURE = typeof GET_PODCAST_FAILURE;
