export const SET_SEARCHSORTBY_START = 'SET_SEARCHSORTBY_START';
export const SET_SEARCHSORTBY_SUCCESS = 'SET_SEARCHSORTBY_SUCCESS';
export const SET_SEARCHSORTBY_FAILUR = 'SET_SEARCHSORTBY_FAILUR';

export type SET_SEARCHSORTBY_START = typeof SET_SEARCHSORTBY_START;
export type SET_SEARCHSORTBY_SUCCESS = typeof SET_SEARCHSORTBY_SUCCESS;
export type SET_SEARCHSORTBY_FAILUR = typeof SET_SEARCHSORTBY_FAILUR;
