export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export type USER_LOGIN_START = typeof USER_LOGIN_START;
export type USER_LOGIN_SUCCESS = typeof USER_LOGIN_SUCCESS;
export type USER_LOGIN_FAILURE = typeof USER_LOGIN_FAILURE;
