export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILUR = 'USER_LOGIN_FAILUR';

export type USER_LOGIN_START = typeof USER_LOGIN_START;
export type USER_LOGIN_SUCCESS = typeof USER_LOGIN_SUCCESS;
export type USER_LOGIN_FAILUR = typeof USER_LOGIN_FAILUR;
