export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export type CREATE_USER_START = typeof CREATE_USER_START;
export type CREATE_USER_SUCCESS = typeof CREATE_USER_SUCCESS;
export type CREATE_USER_FAILURE = typeof CREATE_USER_FAILURE;
