export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILUR = 'CREATE_USER_FAILUR';

export type CREATE_USER_START = typeof CREATE_USER_START;
export type CREATE_USER_SUCCESS = typeof CREATE_USER_SUCCESS;
export type CREATE_USER_FAILUR = typeof CREATE_USER_FAILUR;
