export const USER_LOGOUT_START = 'USER_LOGOUT_START';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

export type USER_LOGOUT_START = typeof USER_LOGOUT_START;
export type USER_LOGOUT_SUCCESS = typeof USER_LOGOUT_SUCCESS;
export type USER_LOGOUT_FAILURE = typeof USER_LOGOUT_FAILURE;
