const ActionTypes = {
  USER_LOGIN_START: 'USER_LOGIN_START',
  USER_LOGIN_SUCESS: 'USER_LOGIN_SUCESS',
  USER_LOGIN_FAILUR: 'USER_LOGIN_FAILUR',
  USER_LOGOUT_START: 'USER_LOGOUT_START',
  USER_LOGOUT_SUCESS: 'USER_LOGOUT_SUCESS',
  USER_LOGOUT_FAILUR: 'USER_LOGOUT_FAILUR',
  USER_REGISTRATION_START: 'USER_REGISTRATION_START',
  USER_REGISTRATION_SUCESS: 'USER_REGISTRATION_SUCESS',
  USER_REGISTRATION_FAILUR: 'USER_REGISTRATION_FAILUR',
};

export default ActionTypes;
