const ActionTypes = {
  USER_LOGIN_START: 'USER_LOGIN_START',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILUR: 'USER_LOGIN_FAILUR',
  USER_LOGOUT_START: 'USER_LOGOUT_START',
  USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
  USER_LOGOUT_FAILUR: 'USER_LOGOUT_FAILUR',
  USER_REGISTRATION_START: 'USER_REGISTRATION_START',
  USER_REGISTRATION_SUCCESS: 'USER_REGISTRATION_SUCCESS',
  USER_REGISTRATION_FAILUR: 'USER_REGISTRATION_FAILUR',
  GET_SELF_SUCCESS: 'GET_SELF_SUCCESS',
};

export default ActionTypes;
