export const GET_FOLLOWING_EVENTS_START = 'GET_FOLLOWING_EVENTS_START';
export const GET_FOLLOWING_EVENTS_SUCCESS = 'GET_FOLLOWING_EVENTS_SUCCESS';
export const GET_FOLLOWING_EVENTS_FAILURE = 'GET_FOLLOWING_EVENTS_FAILURE';

export type GET_FOLLOWING_EVENTS_START = typeof GET_FOLLOWING_EVENTS_START;
export type GET_FOLLOWING_EVENTS_SUCCESS = typeof GET_FOLLOWING_EVENTS_SUCCESS;
export type GET_FOLLOWING_EVENTS_FAILURE = typeof GET_FOLLOWING_EVENTS_FAILURE;
