export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILUR = 'UPDATE_USER_FAILUR';

export type UPDATE_USER_START = typeof UPDATE_USER_START;
export type UPDATE_USER_SUCCESS = typeof UPDATE_USER_SUCCESS;
export type UPDATE_USER_FAILUR = typeof UPDATE_USER_FAILUR;
