export const GET_SUBSCRIPTIONS_START = 'GET_SUBSCRIPTIONS_START';
export const GET_SUBSCRIPTIONS_SUCCESS = 'GET_SUBSCRIPTIONS_SUCCESS';
export const GET_SUBSCRIPTIONS_FAILURE = 'GET_SUBSCRIPTIONS_FAILURE';

export type GET_SUBSCRIPTIONS_START = typeof GET_SUBSCRIPTIONS_START;
export type GET_SUBSCRIPTIONS_SUCCESS = typeof GET_SUBSCRIPTIONS_SUCCESS;
export type GET_SUBSCRIPTIONS_FAILURE = typeof GET_SUBSCRIPTIONS_FAILURE;
