export const GET_SUBSCRIPTIONS_START = 'GET_SUBSCRIPTIONS_START';
export const GET_SUBSCRIPTIONS_SUCCESS = 'GET_SUBSCRIPTIONS_SUCCESS';
export const GET_SUBSCRIPTIONS_FAILUR = 'GET_SUBSCRIPTIONS_FAILUR';

export type GET_SUBSCRIPTIONS_START = typeof GET_SUBSCRIPTIONS_START;
export type GET_SUBSCRIPTIONS_SUCCESS = typeof GET_SUBSCRIPTIONS_SUCCESS;
export type GET_SUBSCRIPTIONS_FAILUR = typeof GET_SUBSCRIPTIONS_FAILUR;
