const ActionTypes = {
  START_PLAYBACK: 'START_PLAYBACK',
  STOP_PLAYBACK: 'STOP_PLAYBACK',
  SET_EPISODE: 'SET_EPISODE',
  DOWNLOAD_EPISODE_START: 'DOWNLOAD_EPISODE_START',
  DOWNLOAD_EPISODE_SUCCESS: 'DOWNLOAD_EPISODE_SUCCESS',
  DOWNLOAD_EPISODE_FAILURE: 'DOWNLOAD_EPISODE_FAILURE',
};

export default ActionTypes;
