export const START_PLAYBACK = 'START_PLAYBACK';
export const STOP_PLAYBACK = 'STOP_PLAYBACK';
export const SET_PLAYER_EPISODE = 'SET_PLAYER_EPISODE';
export const DOWNLOAD_EPISODE_START = 'DOWNLOAD_EPISODE_START';
export const DOWNLOAD_EPISODE_SUCCESS = 'DOWNLOAD_EPISODE_SUCCESS';
export const DOWNLOAD_EPISODE_FAILURE = 'DOWNLOAD_EPISODE_FAILURE';

export type START_PLAYBACK = typeof START_PLAYBACK;
export type STOP_PLAYBACK = typeof STOP_PLAYBACK;
export type SET_PLAYER_EPISODE = typeof SET_PLAYER_EPISODE;
export type DOWNLOAD_EPISODE_START = typeof DOWNLOAD_EPISODE_START;
export type DOWNLOAD_EPISODE_SUCCESS = typeof DOWNLOAD_EPISODE_SUCCESS;
export type DOWNLOAD_EPISODE_FAILURE = typeof DOWNLOAD_EPISODE_FAILURE;
