export const CREATE_USER_EVENT_START = 'CREATE_USER_EVENT_START';
export const CREATE_USER_EVENT_SUCCESS = 'CREATE_USER_EVENT_SUCCESS';
export const CREATE_USER_EVENT_FAILURE = 'CREATE_USER_EVENT_FAILURE';

export type CREATE_USER_EVENT_START = typeof CREATE_USER_EVENT_START;
export type CREATE_USER_EVENT_SUCCESS = typeof CREATE_USER_EVENT_SUCCESS;
export type CREATE_USER_EVENT_FAILURE = typeof CREATE_USER_EVENT_FAILURE;
