export const GET_PODCAST_RATINGS_START = 'GET_PODCAST_RATINGS_START';
export const GET_PODCAST_RATINGS_SUCCESS = 'GET_PODCAST_RATINGS_SUCCESS';
export const GET_PODCAST_RATINGS_FAILURE = 'GET_PODCAST_RATINGS_FAILURE';

export type GET_PODCAST_RATINGS_START = typeof GET_PODCAST_RATINGS_START;
export type GET_PODCAST_RATINGS_SUCCESS = typeof GET_PODCAST_RATINGS_SUCCESS;
export type GET_PODCAST_RATINGS_FAILURE = typeof GET_PODCAST_RATINGS_FAILURE;
