export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export type GET_USERS_START = typeof GET_USERS_START;
export type GET_USERS_SUCCESS = typeof GET_USERS_SUCCESS;
export type GET_USERS_FAILURE = typeof GET_USERS_FAILURE;
