const ActionTypes = {
  UPDATE_USER_START: 'UPDATE_USER_START',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILUR: 'UPDATE_USER_FAILUR',
  GET_USER_START: 'GET_USER_START',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILUR: 'GET_USER_FAILUR',
  GET_SUBSCRIPTIONS_START: 'GET_SUBSCRIPTIONS_START',
  GET_SUBSCRIPTIONS_SUCCESS: 'GET_SUBSCRIPTIONS_SUCCESS',
  GET_SUBSCRIPTIONS_FAILUR: 'GET_SUBSCRIPTIONS_FAILUR',
  CREATE_CATEGORY_START: 'CREATE_CATEGORY_START',
  CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
  CREATE_CATEGORY_FAILUR: 'CREATE_CATEGORY_FAILUR',
  UPDATE_CATEGORY_START: 'UPDATE_CATEGORY_START',
  UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
  UPDATE_CATEGORY_FAILUR: 'UPDATE_CATEGORY_FAILUR',
  DELETE_CATEGORY_START: 'DELETE_CATEGORY_START',
  DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
  DELETE_CATEGORY_FAILUR: 'DELETE_CATEGORY_FAILUR',
};

export default ActionTypes;
