export const SET_SEARCHTYPE_START = 'SET_SEARCHTYPE_START';
export const SET_SEARCHTYPE_SUCCESS = 'SET_SEARCHTYPE_SUCCESS';
export const SET_SEARCHTYPE_FAILUR = 'SET_SEARCHTYPE_FAILUR';

export type SET_SEARCHTYPE_START = typeof SET_SEARCHTYPE_START;
export type SET_SEARCHTYPE_SUCCESS = typeof SET_SEARCHTYPE_SUCCESS;
export type SET_SEARCHTYPE_FAILUR = typeof SET_SEARCHTYPE_FAILUR;
