export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export type DELETE_USER_START = typeof DELETE_USER_START;
export type DELETE_USER_SUCCESS = typeof DELETE_USER_SUCCESS;
export type DELETE_USER_FAILURE = typeof DELETE_USER_FAILURE;
