export const UPDATE_NOTIFICATION_START = 'UPDATE_NOTIFICATION_START';
export const UPDATE_NOTIFICATION_SUCCESS = 'UPDATE_NOTIFICATION_SUCCESS';
export const UPDATE_NOTIFICATION_FAILURE = 'UPDATE_NOTIFICATION_FAILURE';

export type UPDATE_NOTIFICATION_START = typeof UPDATE_NOTIFICATION_START;
export type UPDATE_NOTIFICATION_SUCCESS = typeof UPDATE_NOTIFICATION_SUCCESS;
export type UPDATE_NOTIFICATION_FAILURE = typeof UPDATE_NOTIFICATION_FAILURE;
