export const SET_SEARCHSORTING_START = 'SET_SEARCHSORTING_START';
export const SET_SEARCHSORTING_SUCCESS = 'SET_SEARCHSORTING_SUCCESS';
export const SET_SEARCHSORTING_FAILUR = 'SET_SEARCHSORTING_FAILUR';

export type SET_SEARCHSORTING_START = typeof SET_SEARCHSORTING_START;
export type SET_SEARCHSORTING_SUCCESS = typeof SET_SEARCHSORTING_SUCCESS;
export type SET_SEARCHSORTING_FAILUR = typeof SET_SEARCHSORTING_FAILUR;
