export const SET_SEARCHSORTING_START = 'SET_SEARCHSORTING_START';
export const SET_SEARCHSORTING_SUCCESS = 'SET_SEARCHSORTING_SUCCESS';
export const SET_SEARCHSORTING_FAILURE = 'SET_SEARCHSORTING_FAILURE';

export type SET_SEARCHSORTING_START = typeof SET_SEARCHSORTING_START;
export type SET_SEARCHSORTING_SUCCESS = typeof SET_SEARCHSORTING_SUCCESS;
export type SET_SEARCHSORTING_FAILURE = typeof SET_SEARCHSORTING_FAILURE;
