export const GET_EPISODE_START = 'GET_EPISODE_START';
export const GET_EPISODE_SUCCESS = 'GET_EPISODE_SUCCESS';
export const GET_EPISODE_FAILURE = 'GET_EPISODE_FAILURE';

export type GET_EPISODE_START = typeof GET_EPISODE_START;
export type GET_EPISODE_SUCCESS = typeof GET_EPISODE_SUCCESS;
export type GET_EPISODE_FAILURE = typeof GET_EPISODE_FAILURE;
