export const UPDATE_CATEGORY_START = 'UPDATE_CATEGORY_START';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAILUR = 'UPDATE_CATEGORY_FAILUR';

export type UPDATE_CATEGORY_START = typeof UPDATE_CATEGORY_START;
export type UPDATE_CATEGORY_SUCCESS = typeof UPDATE_CATEGORY_SUCCESS;
export type UPDATE_CATEGORY_FAILUR = typeof UPDATE_CATEGORY_FAILUR;
