export const SET_SEARCHFILTERS_START = 'SET_SEARCHFILTERS_START';
export const SET_SEARCHFILTERS_SUCCESS = 'SET_SEARCHFILTERS_SUCCESS';
export const SET_SEARCHFILTERS_FAILURE = 'SET_SEARCHFILTERS_FAILURE';

export type SET_SEARCHFILTERS_START = typeof SET_SEARCHFILTERS_START;
export type SET_SEARCHFILTERS_SUCCESS = typeof SET_SEARCHFILTERS_SUCCESS;
export type SET_SEARCHFILTERS_FAILURE = typeof SET_SEARCHFILTERS_FAILURE;
