export const SET_SEARCHFILTERS_START = 'SET_SEARCHFILTERS_START';
export const SET_SEARCHFILTERS_SUCCESS = 'SET_SEARCHFILTERS_SUCCESS';
export const SET_SEARCHFILTERS_FAILUR = 'SET_SEARCHFILTERS_FAILUR';

export type SET_SEARCHFILTERS_START = typeof SET_SEARCHFILTERS_START;
export type SET_SEARCHFILTERS_SUCCESS = typeof SET_SEARCHFILTERS_SUCCESS;
export type SET_SEARCHFILTERS_FAILUR = typeof SET_SEARCHFILTERS_FAILUR;
