const ActionTypes = {
  GET_TOP_PODCASTS_START: 'GET_TOP_PODCASTS_START',
  GET_TOP_PODCASTS_SUCCESS: 'GET_TOP_PODCASTS_SUCCESS',
  GET_TOP_PODCASTS_FAILURE: 'GET_TOP_PODCASTS_FAILURE',

};

export default ActionTypes;
