export const TOGGLE_FOLLOWS_START = 'TOGGLE_FOLLOWS_START';
export const TOGGLE_FOLLOWS_SUCCESS = 'TOGGLE_FOLLOWS_SUCCESS';
export const TOGGLE_FOLLOWS_FAILURE = 'TOGGLE_FOLLOWS_FAILURE';

export type TOGGLE_FOLLOWS_START = typeof TOGGLE_FOLLOWS_START;
export type TOGGLE_FOLLOWS_SUCCESS = typeof TOGGLE_FOLLOWS_SUCCESS;
export type TOGGLE_FOLLOWS_FAILURE = typeof TOGGLE_FOLLOWS_FAILURE;
