
export const CREATE_CATEGORY_START = 'CREATE_CATEGORY_START';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAILURE = 'CREATE_CATEGORY_FAILURE';

export type CREATE_CATEGORY_START = typeof CREATE_CATEGORY_START;
export type CREATE_CATEGORY_SUCCESS = typeof CREATE_CATEGORY_SUCCESS;
export type CREATE_CATEGORY_FAILURE = typeof CREATE_CATEGORY_FAILURE;
