export const SEARCH_START = 'SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export type SEARCH_START = typeof SEARCH_START;
export type SEARCH_SUCCESS = typeof SEARCH_SUCCESS;
export type SEARCH_FAILURE = typeof SEARCH_FAILURE;
