export const USER_REGISTRATION_START = 'USER_REGISTRATION_START';
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
export const USER_REGISTRATION_FAILURE = 'USER_REGISTRATION_FAILURE';

export type USER_REGISTRATION_START = typeof USER_REGISTRATION_START;
export type USER_REGISTRATION_SUCCESS = typeof USER_REGISTRATION_SUCCESS;
export type USER_REGISTRATION_FAILURE = typeof USER_REGISTRATION_FAILURE;
