const ActionTypes = {
  SET_SEARCHTYPE_START: 'SET_SEARCHTYPE_START',
  SET_SEARCHTYPE_SUCCESS: 'SET_SEARCHTYPE_SUCCESS',
  SET_SEARCHTYPE_FAILUR: 'SET_SEARCHTYPE_FAILUR',
  SET_SEARCHFILTERS_START: 'SET_SEARCHFILTERS_START',
  SET_SEARCHFILTERS_SUCCESS: 'SET_SEARCHFILTERS_SUCCESS',
  SET_SEARCHFILTERS_FAILUR: 'SET_SEARCHFILTERS_FAILUR',
  SET_SEARCHSORTBY_START: 'SET_SEARCHSORTBY_START',
  SET_SEARCHSORTBY_SUCCESS: 'SET_SEARCHSORTBY_SUCCESS',
  SET_SEARCHSORTBY_FAILUR: 'SET_SEARCHSORTBY_FAILUR',
  SEARCH_START: 'SEARCH_START',
  SEARCH_SUCCESS: 'SEARCH_SUCCESS',
  SEARCH_FAILUR: 'SEARCH_FAILUR',
};

export default ActionTypes;
