const ActionTypes = {
  SET_SEARCHTYPE_START: 'SET_SEARCHTYPE_START',
  SET_SEARCHTYPE_SUCESS: 'SET_SEARCHTYPE_SUCESS',
  SET_SEARCHTYPE_FAILUR: 'SET_SEARCHTYPE_FAILUR',
  SET_SEARCHFILTERS_START: 'SET_SEARCHFILTERS_START',
  SET_SEARCHFILTERS_SUCESS: 'SET_SEARCHFILTERS_SUCESS',
  SET_SEARCHFILTERS_FAILUR: 'SET_SEARCHFILTERS_FAILUR',
  SET_SEARCHSORTBY_START: 'SET_SEARCHSORTBY_START',
  SET_SEARCHSORTBY_SUCESS: 'SET_SEARCHSORTBY_SUCESS',
  SET_SEARCHSORTBY_FAILUR: 'SET_SEARCHSORTBY_FAILUR',
};

export default ActionTypes;
