
export const SET_SEARCHTYPE_START = 'SET_SEARCHTYPE_START';
export const SET_SEARCHTYPE_SUCCESS = 'SET_SEARCHTYPE_SUCCESS';
export const SET_SEARCHTYPE_FAILUR = 'SET_SEARCHTYPE_FAILUR';
export const SET_SEARCHFILTERS_START = 'SET_SEARCHFILTERS_START';
export const SET_SEARCHFILTERS_SUCCESS = 'SET_SEARCHFILTERS_SUCCESS';
export const SET_SEARCHFILTERS_FAILUR = 'SET_SEARCHFILTERS_FAILUR';
export const SET_SEARCHSORTBY_START = 'SET_SEARCHSORTBY_START';
export const SET_SEARCHSORTBY_SUCCESS = 'SET_SEARCHSORTBY_SUCCESS';
export const SET_SEARCHSORTBY_FAILUR = 'SET_SEARCHSORTBY_FAILUR';
export const SEARCH_START = 'SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILUR = 'SEARCH_FAILUR';

export type SET_SEARCHTYPE_START = typeof SET_SEARCHTYPE_START;
export type SET_SEARCHTYPE_SUCCESS = typeof SET_SEARCHTYPE_SUCCESS;
export type SET_SEARCHTYPE_FAILUR = typeof SET_SEARCHTYPE_FAILUR;
export type SET_SEARCHFILTERS_START = typeof SET_SEARCHFILTERS_START;
export type SET_SEARCHFILTERS_SUCCESS = typeof SET_SEARCHFILTERS_SUCCESS;
export type SET_SEARCHFILTERS_FAILUR = typeof SET_SEARCHFILTERS_FAILUR;
export type SET_SEARCHSORTBY_START = typeof SET_SEARCHSORTBY_START;
export type SET_SEARCHSORTBY_SUCCESS = typeof SET_SEARCHSORTBY_SUCCESS;
export type SET_SEARCHSORTBY_FAILUR = typeof SET_SEARCHSORTBY_FAILUR;
export type SEARCH_START = typeof SEARCH_START;
export type SEARCH_SUCCESS = typeof SEARCH_SUCCESS;
export type SEARCH_FAILUR = typeof SEARCH_FAILUR;
