const ActionTypes = {
  GET_USERS_START: 'GET_USERS_START',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILUR: 'GET_USERS_FAILUR',
  ADMIN_UPDATE_USER_START: 'ADMIN_UPDATE_USER_START',
  ADMIN_UPDATE_USER_SUCCESS: 'ADMIN_UPDATE_USER_SUCCESS',
  ADMIN_UPDATE_USER_FAILUR: 'ADMIN_UPDATE_USER_FAILUR',
  DELETE_USER_START: 'DELETE_USER_START',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILUR: 'DELETE_USER_FAILUR',
  CREATE_USER_START: 'CREATE_USER_START',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILUR: 'CREATE_USER_FAILUR',
  SET_USER: 'SET_USER',
  UNSET_USER: 'UNSET_USER',
};

export default ActionTypes;
