export const DELETE_NOTIFICATION_START = 'DELETE_NOTIFICATION_START';
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';
export const DELETE_NOTIFICATION_FAILURE = 'DELETE_NOTIFICATION_FAILURE';

export type DELETE_NOTIFICATION_START = typeof DELETE_NOTIFICATION_START;
export type DELETE_NOTIFICATION_SUCCESS = typeof DELETE_NOTIFICATION_SUCCESS;
export type DELETE_NOTIFICATION_FAILURE = typeof DELETE_NOTIFICATION_FAILURE;
