export const DELETE_CATEGORY_START = 'DELETE_CATEGORY_START';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE';

export type DELETE_CATEGORY_START = typeof DELETE_CATEGORY_START;
export type DELETE_CATEGORY_SUCCESS = typeof DELETE_CATEGORY_SUCCESS;
export type DELETE_CATEGORY_FAILURE = typeof DELETE_CATEGORY_FAILURE;
