export const DELETE_CATEGORY_START = 'DELETE_CATEGORY_START';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILUR = 'DELETE_CATEGORY_FAILUR';

export type DELETE_CATEGORY_START = typeof DELETE_CATEGORY_START;
export type DELETE_CATEGORY_SUCCESS = typeof DELETE_CATEGORY_SUCCESS;
export type DELETE_CATEGORY_FAILUR = typeof DELETE_CATEGORY_FAILUR;
