export const ADMIN_UPDATE_USER_START = 'ADMIN_UPDATE_USER_START';
export const ADMIN_UPDATE_USER_SUCCESS = 'ADMIN_UPDATE_USER_SUCCESS';
export const ADMIN_UPDATE_USER_FAILUR = 'ADMIN_UPDATE_USER_FAILUR';

export type ADMIN_UPDATE_USER_START = typeof ADMIN_UPDATE_USER_START;
export type ADMIN_UPDATE_USER_SUCCESS = typeof ADMIN_UPDATE_USER_SUCCESS;
export type ADMIN_UPDATE_USER_FAILUR = typeof ADMIN_UPDATE_USER_FAILUR;
