export const TOGGLE_SUBSCRIPTION_START = 'TOGGLE_SUBSCRIPTION_START';
export const TOGGLE_SUBSCRIPTION_SUCCESS = 'TOGGLE_SUBSCRIPTION_SUCCESS';
export const TOGGLE_SUBSCRIPTION_FAILURE = 'TOGGLE_SUBSCRIPTION_FAILURE';

export type TOGGLE_SUBSCRIPTION_START = typeof TOGGLE_SUBSCRIPTION_START;
export type TOGGLE_SUBSCRIPTION_SUCCESS = typeof TOGGLE_SUBSCRIPTION_SUCCESS;
export type TOGGLE_SUBSCRIPTION_FAILURE = typeof TOGGLE_SUBSCRIPTION_FAILURE;
