const ActionTypes = {
  TOGGLE_SUBSCRIPTION_START: 'TOGGLE_SUBSCRIPTION_START',
  TOGGLE_SUBSCRIPTION_SUCCESS: 'TOGGLE_SUBSCRIPTION_SUCCESS',
  TOGGLE_SUBSCRIPTION_FAILUR: 'TOGGLE_SUBSCRIPTION_FAILUR',

};

export default ActionTypes;
